spring:
  profiles:
    active: dev
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.zhang.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#Eureka配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance-id: springcloud-provider-dept-8001   #修改Eureka上的默认扫描信息
  instance:
    hostname: localhost #设置当前实例的主机名

#info配置 监控信息 表示微服务是谁写的
info:
  app.name: zhang-springcloud
  company.name: blog.zhang.com
  
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.zhang.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#Eureka配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance-id: springcloud-provider-dept-8001   #修改Eureka上的默认扫描信息
  instance:
    hostname: localhost #设置当前实例的主机名

#info配置 监控信息 表示微服务是谁写的
info:
  app.name: zhang-springcloud
  company.name: blog.zhang.com
